

package arteelectronico;
import javax.swing.JOptionPane;
import java.util.Random;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class Texto extends javax.swing.JFrame {

    /**
     * Creates new form Texto
     */
    public Texto() {
        initComponents();
        o3.setVisible(false);
        o4.setVisible(false);
        o5.setVisible(false);
        o6.setVisible(false);
        String Opciones1[] = {"\"Cuando encuentra el apartamento que quería, empieza \\na llamar al camión de la mudanza, esperando en la acera \\na que el camión llegue se encuentre con un indigente que \\nle pide dinero ella lo observa y le da 4 mil pesos porque \\nsabe que ese hombre debe de estar pasando hambre; muy a su\\npesar el hombre se levanta se mete a la tienda que queda\\nenfrente de su casa a comprar alcohol y emborracharse. \\n\"\n" +
"                + \"El camión de mudanza nunca llega, llegaría dentro de \\nun día , porque los hombres se perdieron por \\nel camino peligroso y nada transitado. \\n\"\n" +
"                "
                + "+ \"Al día siguiente tiene que llevar ropa que ya ha usado \\nporque la mudanza nada que llegaba a sus clases \\nregulares y para cuando vuelve el camión ya está esperándola \\ny comienza a descargar sus cosas. \\n\";",
                 
            "Luego de elegir el apartamento que quiere, llama al \ncamión de la mudanza y mientras espera ve a un indigente que \nle pide dinero, ella en cambio le da comida, porque sabe \nque ese hombre debe de tener hambre, el hombre la mira con \nojos tiernos y devora la comida que la chica le dió. \n"
                + "El camión de la mudanza llega y ella empieza a descargar \nsus cosas. "};
        
        String Opciones2[] = {"La chica elige sushi y espera su pedido, cuando llega \nella lo devora sin dejar nada, pero lastimosamente se \ndespierta a medianoche a vomitar porque el pescado crudo le cayó mal. \nY se verá obligada a estar yendo al baño cada cierto \ntiempo, pero no puede faltar a clases porque tiene un \nquiz muy importante.",
            "La chica elige pizza y espera su pedido, cuando llega \nse come la mitad y deja algunos pedazos para que desayune \nal día siguiente."};
        
        String Opciones3[] = {"\"Le pregunta qué le pasa, él le cuenta que está triste porque \\ quiere dejar el alcohol pero se le hace muy difícil \\ ella decide aconsejarle que se meta en \\ un grupo de alcohólicos anónimos y reduzca las dosis de alcohol poco a poco \\ no lo suspenda tan bruscamente porque la ansiedad que sentirán sera peor \\ el le agradece sus consejos le da las botellas de cerveza que tiene escondidas \\ y le pide que las arroje a la basura,\\ solo se quedaría con una, ella hace y le desea buenas noches a Jaime \\ y sube a su apartamento.\n" +
"\"A la mañana siguiente cuando ella se dirige a la universidad se encuentra a Jaime \\ y este le cuenta que ya se inscribió a un grupo de alcohólicos y hoy es su primera cita,\\ ella le dice que si quiere después de que llegue de la universidad \\ puede ir a asearse a su apartamento para ir bien presentado,\\ a pesar de no ser una entrevista él quiere hacer lo mejor \\ porque es algo supremamente importante para el, Jaime acepta contento la oferta de la chica. \n" +
"\"jaime va a su reunión y se siente muy bien, \\ decide ir a contarle a la chica y ella lo felicita Jaime \\ está muy feliz por su avance.",
            
            "\"hacen contacto visual y sigue su camino hasta llegar a su apartamento\\ pero los sollozos de Jaime no la dejan dormir.\n" +
"\"a la mañana siguiente ve a Jaime con los ojos rojos de tanto llorar \\ y ella igual porque no pudo pegar ojo en toda la noche por los sollozos de él \\ se siente fatal por no haberlo ayudado, pero ella no le debe nada,\\  decide seguir de largo e irse a la universidad.\\ cuando ella vuelve de la universidad encuentra a Jaime borracho lleno de basura.\\ decide no mirar y sube a su apartamento, escucha golpes, Jaime está recibiendo una paliza,\\ lo dejan tendido en el piso, ella solo puede mirar, no puede hacer más nada, \\ al fin de cuentas él no es su papá"};
       
        String Opciones4[] = {"Decirle que ella es su hija ","Decirle que lo mejor es que siga con su vida"};
        
        
        String Opciones6[] = {"Jaime acepta","Jaime Rechaza"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        o2 = new javax.swing.JButton();
        o1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        o3 = new javax.swing.JButton();
        o4 = new javax.swing.JButton();
        o5 = new javax.swing.JButton();
        o6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        area.setRows(5);
        area.setText("Una chica que está en segundo año \nde derecho ha vuelto a la ciudad \ndonde creció después de haber hecho \nsu primer año en otro país. Está buscando \napartamentos que queden cerca de su \nuniversidad para que todo sea más fácil. \nEncuentra dos apartamentos \n1. 5 minutos de la universidad pero por un camino \ntotalmente solo y peligroso \n2. 20 minutos de la universidad pero por un camino \nmás transitado, pero al ser más transitado ocurren \nmuchos trancones. \n");
        jScrollPane1.setViewportView(area);

        o2.setText("op2");
        o2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o2ActionPerformed(evt);
            }
        });

        o1.setText("op1");
        o1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Opcion 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Opcion 2");

        o3.setText("op3");
        o3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o3ActionPerformed(evt);
            }
        });

        o4.setText("op4");
        o4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o4ActionPerformed(evt);
            }
        });

        o5.setText("op5");
        o5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o5ActionPerformed(evt);
            }
        });

        o6.setText("op6");
        o6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(o6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o1ActionPerformed
        String txt = "Cuando encuentra el apartamento que quería, empieza \na llamar al camión de la mudanza, esperando en la acera \na que el camión llegue se encuentre con un indigente que \nle pide dinero ella lo observa y le da 4 mil pesos porque \nsabe que ese hombre debe de estar pasando hambre; muy a su\npesar el hombre se levanta se mete a la tienda que queda\nenfrente de su casa a comprar alcohol y emborracharse. \n"
                + "El camión de mudanza nunca llega, llegaría dentro de \nun día , porque los hombres se perdieron por \nel camino peligroso y nada transitado. \n"
                + "Al día siguiente tiene que llevar ropa que ya ha usado \nporque la mudanza nada que llegaba a sus clases \nregulares y para cuando vuelve el camión ya está esperándola \ny comienza a descargar sus cosas. \n";
        o1.setVisible(false);
        o2.setVisible(false);
        o3.setVisible(true);
        o4.setVisible(true);
        String txt2 = "Cuando ya ha terminado de acomodar todo, cuyo procesos le \nllevó 3 días está cansada y hambrienta decide ordenar \ncomida por rappi, tiene 15k en rappicreditos si come\nsushi le saldrá totalmente gratis, pero si coge \npizza tendrá que pagar 3k demás. ";
        area.setText(txt + txt2);


    }//GEN-LAST:event_o1ActionPerformed

    private void o4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o4ActionPerformed
        String txt = "La chica elige pizza y espera su pedido, cuando llega \nse come la mitad y deja algunos pedazos para que desayune \nal día siguiente.";
        o3.setVisible(false);
        o4.setVisible(false);
        o5.setVisible(true);
        o6.setVisible(true);
        String txt2 = "A la mañana siguiente se va a la universidad y se \nencuentra al indigente este la saluda alegremente, hay \nalgo en el que le recuerda a alguien pero no sabe a quien, \ncuando va caminando alguien grita su apellido y ella y \nel indigente voltean al mismo tiempo, ambos se miran extrañados.\n"
                + "Señor: ¿Es usted apellido Perez señorita? \nHola, mi nombre es Jaime Perez.\n"
                + "Ella sorprendida se da cuenta que el es su padre, el \nque la abandonó cuando era muy pequeña porque el tenia \nproblemas con el alcohol.\n"
                + "Chica: Hola, mi nombre es Julia Pérez (miente)\n"
                + "Señor: ¡vaya! tenemos el mismo apellido, que coincidencia\n"
                + "la chica se despide del hombre y se dirige al paradero \nde buses, ella pensó que sentiría rabia al ver al hombre\nque le dio la vida pero que la abandonó a ella y a su \nmama despues de tantos años, pero sorprendentemente siente \nmucha pena por él, en el estado en el que está, se \ndejó consumir por el alcohol.\n"
                + "la chica va a clase regular y cuando llega al \nedificio, encuentra a Jaime que está llorando.";
        area.setText(txt + txt2);

    }//GEN-LAST:event_o4ActionPerformed

    private void o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o2ActionPerformed
        String txt = "Luego de elegir el apartamento que quiere, llama al \ncamión de la mudanza y mientras espera ve a un indigente que \nle pide dinero, ella en cambio le da comida, porque sabe \nque ese hombre debe de tener hambre, el hombre la mira con \nojos tiernos y devora la comida que la chica le dió. \n"
                + "El camión de la mudanza llega y ella empieza a descargar \nsus cosas. ";
        o1.setVisible(false);
        o2.setVisible(false);
        o3.setVisible(true);
        o4.setVisible(true);
        String txt2 = "Cuando ya ha terminado de acomodar todo, cuyo procesos le \nllevó 3 días está cansada y hambrienta decide ordenar \ncomida por rappi, tiene 15k en rappicreditos si come\nsushi le saldrá totalmente gratis, pero si coge \npizza tendrá que pagar 3k demás. ";
        area.setText(txt + txt2);

    }//GEN-LAST:event_o2ActionPerformed

    private void o3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o3ActionPerformed
        String txt = "La chica elige sushi y espera su pedido, cuando llega \nella lo devora sin dejar nada, pero lastimosamente se \ndespierta a medianoche a vomitar porque el pescado crudo le cayó mal. \nY se verá obligada a estar yendo al baño cada cierto \ntiempo, pero no puede faltar a clases porque tiene un \nquiz muy importante.";
        o3.setVisible(false);
        o4.setVisible(false);
        o5.setVisible(true);
        o6.setVisible(true);
        String txt2 = "A la mañana siguiente se va a la universidad y se \nencuentra al indigente este la saluda alegremente, hay \nalgo en el que le recuerda a alguien pero no sabe a quien, \ncuando va caminando alguien grita su apellido y ella y \nel indigente voltean al mismo tiempo, ambos se miran extrañados.\n"
                + "Señor: ¿Es usted apellido Perez señorita? \nHola, mi nombre es Jaime Perez.\n"
                + "Ella sorprendida se da cuenta que el es su padre, el \nque la abandonó cuando era muy pequeña porque el tenia \nproblemas con el alcohol.\n"
                + "Chica: Hola, mi nombre es Julia Pérez (miente)\n"
                + "Señor: ¡vaya! tenemos el mismo apellido, que coincidencia\n"
                + "la chica se despide del hombre y se dirige al paradero \nde buses, ella pensó que sentiría rabia al ver al hombre\nque le dio la vida pero que la abandonó a ella y a su \nmama despues de tantos años, pero sorprendentemente siente \nmucha pena por él, en el estado en el que está, se \ndejó consumir por el alcohol.\n"
                + "la chica va a clase regular y cuando llega al \nedificio, encuentra a Jaime que está llorando.";
        area.setText(txt + txt2);

    }//GEN-LAST:event_o3ActionPerformed

    private void o5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o5ActionPerformed
        String txt = "Le pregunta qué le pasa, él le cuenta que está triste \nporque quiere dejar el alcohol pero se le hace muy \ndifícil, ella decide aconsejarle que se meta en un grupo \nde alcohólicos anónimos y reduzca las dosis de alcohol \npoco a poco, no lo suspenda tan bruscamente porque la \nansiedad que sentirán sera peor, el le agradece sus consejos le \nda las botellas de cerveza que tiene escondidas y le pide \nque las arroje a la basura, solo se quedaría con una, \nella hace y le desea buenas noches a Jaime y sube a su \napartamento.\n"
                + "A la mañana siguiente cuando ella se dirige a la universidad \nse encuentra a Jaime y este le cuenta que ya se inscribió a \nun grupo de alcohólicos y hoy es su primera cita, ella \nle dice que si quiere después de que llegue de la universidad \npuede ir a asearse a su apartamento para ir bien presentado, \na pesar de no ser una entrevista él quiere hacer lo mejor \nporque es algo supremamente importante para el, Jaime \nacepta contento la oferta de la chica. \n"
                + "jaime va a su reunión y se siente muy bien, decide \nir a contarle a la chica y ella lo felicita Jaime \nestá muy feliz por su avance.";
        o5.setVisible(false);
        o6.setVisible(false);
        String txt2 = "";
        area.setText(txt + txt2);
    }//GEN-LAST:event_o5ActionPerformed

    private void o6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Texto().setVisible(true);
            }
        });
    }
    public static void Random(int Opciones[]){
        Random Generar = new Random();
        for(int i =1;i<=2;i++){
            int Aux = Generar.nextInt(2)+1;
            if(!comprobarNumero(Aux,Opciones)){
                Opciones[i]=Aux;
            }
            else{
                i--;
            }
        }
    }
    public static boolean comprobarNumero(int num,int Al[]){
               for(int i=1;i<=3;i++){
                       if(Al[i]==num){
                            return true;
                       }
               }
               return false;
         }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton o1;
    private javax.swing.JButton o2;
    private javax.swing.JButton o3;
    private javax.swing.JButton o4;
    private javax.swing.JButton o5;
    private javax.swing.JButton o6;
    // End of variables declaration//GEN-END:variables
}
